# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout repd
      uses: actions/checkout@v3
      
    - name: Use Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: ${{matrix.node_version}}
    - name: install npm
      run: npm ci

    - name: project-build
      run: npm run build
    - name: action-zip
      run: zip -r server.zip server 
      
    - name: upload it to github
      uses: actions/upload-artifact@v4
      with:
        name: build-artifact
        path: server.zip


    
    
